// The ten theme blocks — loaded from the canonical source, not restated here.
//
// `intake/themes.json` is generated by `tools/render_intake.py` from `intake/themes/tNN-*.yaml`,
// the same source the two Markdown intake forms are rendered from. Importing it here is what
// makes INV-5 true rather than aspirational: the form, the app and the JSON export cannot drift,
// because there is only one place any of them can drift from. The gate re-renders and diffs.
//
// The import is resolved at build time and inlined into the bundle — no fetch, no network call.
//
// English is the binding language of this repository. German text is a translation and is
// labelled as one wherever it is shown; it is never the source of record. Hypotheses carry no
// German: they are analytical prose where an unmarked translation would quietly become the
// authority, so they stay English and the UI says so.

import source from "../../intake/themes.json";

export type Basis = "fact" | "statement" | "assumption" | "unknown";

/**
 * One filled-in answer. Lives here rather than in App because the deck reads the same
 * structure: the presentation is a projection of these fields, never a rewriting of them.
 *
 * Two groups sit beside the answer itself, and both exist because a reviewer read the
 * instrument as an enterprise architect would and found the same two holes:
 *
 *   - **Where it came from.** The agent specification asks for "speaker and date" beside
 *     every statement, and a single free-text line cannot reliably produce that: the field
 *     held a document name, or a person, or nothing, and no reader could tell which. The
 *     free line stays as the locator — the page, the quote, the ticket — and the artefact,
 *     the person and the date are captured as themselves.
 *   - **What closes it.** An open point with no owner and no date is a note, not a task.
 *     `owner`, `evidence`, `due` and `blocker` are what turn the register from a list of
 *     doubts into work somebody has agreed to do.
 *
 * Older records carry none of these. `hydrate` fills them in on read, so an intake saved
 * before this shape existed still opens — with its old free-text source intact.
 */
export interface Answer {
  text: string;
  basis: Basis | null;
  /** The locator: the quotation, the page, the ticket line. Free text on purpose. */
  source: string;
  /** The document, link or system the answer came out of. */
  artifact: string;
  /** The person who said it — the "speaker" the presentation agent asks for. */
  speaker: string;
  /** The date it was said or the artefact was current. Free text: "2026-03-11", "Q1 2026". */
  sourceDate: string;
  verification: Verification;
  /** Who owes the proof. A role is enough; a name is better. */
  owner: string;
  /** What would actually close it — the document, log, test or written confirmation. */
  evidence: string;
  /** The date by which it is expected. */
  due: string;
  /** What has to happen first, or who is in the way. */
  blocker: string;
  /**
   * This answer holds two accounts that do not agree.
   *
   * Set by hand, never detected. The agent specification keeps a section for exactly this
   * — "Offene Punkte & Konflikte", quoted verbatim, not resolved, not averaged, not silently
   * adopted — and the deck had nowhere to put it, so a contradiction recorded in the room
   * arrived on the slides as an ordinary open point. Both accounts go in `text` as they were
   * said; this flag is what makes the deck carry them under their own heading.
   */
  conflict: boolean;
}

/** An answer nobody has touched. The one place the empty shape is written down. */
export const EMPTY_ANSWER: Answer = {
  text: "",
  basis: null,
  source: "",
  artifact: "",
  speaker: "",
  sourceDate: "",
  verification: "none",
  owner: "",
  evidence: "",
  due: "",
  blocker: "",
  conflict: false,
};

/**
 * Read one stored answer into the current shape.
 *
 * `localStorage` and `demo/case.json` both hold records written against older shapes, and
 * TypeScript cannot help there: the value arrives as `any` from `JSON.parse` and every new
 * field would be `undefined` at runtime, which reaches the UI as an uncontrolled input and
 * the export as the string "undefined". Spreading over the empty shape is the whole fix,
 * and it is applied on read rather than on write so a record only has to survive being
 * opened once.
 */
export function hydrate(a: Partial<Answer> | null | undefined): Answer {
  return a ? { ...EMPTY_ANSWER, ...a } : EMPTY_ANSWER;
}

/**
 * A direction as it was said in the room, with the open points it hangs on.
 *
 * The deck's fourth slide is specified as "Nicht entschiedene Richtungen", each one stated
 * conditionally — "this direction depends on [Q3.2]". Nothing in the intake could carry
 * such a sentence, so the slide fell back to listing open Q-IDs by theme: honest, but not
 * what the specification asks for. This is the missing field, and it is typed by the
 * architect, never generated: INV-7 does not stop applying because a renderer would find it
 * convenient. `dependsOn` is what keeps INV-1 true — a direction with no open point behind
 * it would read as a recommendation, so the deck says so instead of hiding it.
 */
export interface Direction {
  text: string;
  dependsOn: string[];
}

/** The Entscheidungskopf, keyed by the field slots below. */
export type DecisionHead = Record<string, string>;
export type Verification = "none" | "open" | "blocked";
export type Mode = "triage" | "discovery";
export type Lang = "en" | "de";

/** Every human-readable string in the canonical source carries both languages. */
export interface Text {
  en: string;
  de: string;
}

export const pick = (t: Text, lang: Lang): string => t[lang];

export interface Question {
  id: string;
  text: Text;
  /** Security, data protection, regulation, cost, irreversibility: unknown stays unknown. */
  noDefaults?: boolean;
  modes: Mode[];
  /** Scoping guidance carried by a few questions (Q7.3). English, like the hypotheses. */
  note?: string;
  /** An example of the shape a usable answer has, shown while the field is empty.
      Guidance, never a default: it is not carried into an answer nobody gave. */
  hint?: Text;
}

/** A testable pattern with its boundary — never disguised as a question (INV-6). */
export interface Hypothesis {
  name: string;
  scopeOfValidity: string;
  falsifiableBy: string;
}

/** Theme 2 only: the Entscheidungskopf, filled at intake time. */
export interface DecisionHeadField {
  key: string;
  label: Text;
  /** An example of the shape the field wants, shown while it is empty. */
  hint: Text;
}

/** Theme 6 only: the mini data inventory, one row per data domain. */
export interface DataInventory {
  columns: string[];
}

export interface Theme {
  id: number;
  slug: string;
  title: Text;
  /** Two sentences: why this block exists at all. */
  why: Text;
  redFlags: Text[];
  stopConditions: Text[];
  hypotheses: Hypothesis[];
  questions: Question[];
  hasDecisionHead: boolean;
  dataInventory?: DataInventory;
}

interface RawQuestion {
  id: string;
  mode: string[];
  no_defaults: boolean;
  text: Text;
  note?: string;
  hint?: Text;
}

interface RawHypothesis {
  name: string;
  scope_of_validity: string;
  falsifiable_by: string;
}

interface RawTheme {
  theme_id: number;
  slug: string;
  title: Text;
  why: Text;
  questions: RawQuestion[];
  hypotheses?: RawHypothesis[];
  red_flags: Text[];
  stop_conditions: Text[];
  decision_head?: unknown;
  data_inventory_annex?: { columns: string[] };
}

/** The YAML block scalars keep their trailing newlines; the UI wants one paragraph. */
const flatten = (s: string): string => s.replace(/\s+/g, " ").trim();

const flattenText = (t: Text): Text => ({ en: flatten(t.en), de: flatten(t.de) });

export const THEMES: Theme[] = (source.themes as RawTheme[]).map((t) => ({
  id: t.theme_id,
  slug: t.slug,
  title: t.title,
  why: flattenText(t.why),
  redFlags: t.red_flags.map(flattenText),
  stopConditions: t.stop_conditions.map(flattenText),
  hypotheses: (t.hypotheses ?? []).map((h) => ({
    name: h.name,
    scopeOfValidity: flatten(h.scope_of_validity),
    falsifiableBy: flatten(h.falsifiable_by),
  })),
  questions: t.questions.map((q) => ({
    id: q.id,
    text: q.text,
    noDefaults: q.no_defaults || undefined,
    modes: q.mode as Mode[],
    note: q.note ? flatten(q.note) : undefined,
    hint: q.hint,
  })),
  hasDecisionHead: t.decision_head !== undefined,
  dataInventory: t.data_inventory_annex
    ? { columns: t.data_inventory_annex.columns }
    : undefined,
}));

/** The Entscheidungskopf slots, in the order the briefing fixes them. */
export const DECISION_HEAD_FIELDS: DecisionHeadField[] = [
  {
    key: "decision_question",
    label: { en: "Decision question", de: "Entscheidungsfrage" },
    hint: {
      en: "Answerable with yes, no, or a named option, and carrying a date.",
      de: "Mit Ja, Nein oder einer benannten Option beantwortbar, und mit Datum.",
    },
  },
  {
    key: "decision_owner",
    label: { en: "Decision owner", de: "Entscheidungseigner" },
    hint: {
      en: "One named person, and whether the authority is in writing.",
      de: "Eine benannte Person, und ob die Befugnis schriftlich hinterlegt ist.",
    },
  },
  {
    key: "in_scope",
    label: { en: "In scope", de: "Im Scope" },
    hint: {
      en: "The systems and layers this decision is allowed to change.",
      de: "Die Systeme und Schichten, die diese Entscheidung ändern darf.",
    },
  },
  {
    key: "out_of_scope",
    label: { en: "Out of scope", de: "Außerhalb des Scope" },
    hint: {
      en: "What it explicitly does not touch.",
      de: "Was sie ausdrücklich nicht anfasst.",
    },
  },
  {
    key: "deadline",
    label: { en: "Deadline", de: "Frist" },
    hint: {
      en: "The date, and what happens on the day after it passes.",
      de: "Das Datum, und was am Tag danach passiert.",
    },
  },
];

/** Examples for the mini data inventory, keyed by the column name from the theme source. */
export const COLUMN_HINTS: Record<string, Text> = {
  domain: { en: "Partner data", de: "Partnerdaten" },
  classification: { en: "confidential, established 2021", de: "vertraulich, festgestellt 2021" },
  owner: { en: "one named person", de: "eine benannte Person" },
  retention: { en: "10 years after contract end", de: "10 J. nach Vertragsende" },
  erasure_path: { en: "tested, or say it is not", de: "getestet, oder: nicht" },
};

/** Every question in the set, flat — the deck reads answers by Q-ID. */
export const QUESTIONS_BY_ID: ReadonlyMap<string, Question> = new Map(
  THEMES.flatMap((t) => t.questions.map((q) => [q.id, q] as const)),
);
