// The ten theme blocks — loaded from the canonical source, not restated here.
//
// `intake/themes.json` is generated by `tools/render_intake.py` from `intake/themes/tNN-*.yaml`,
// the same source the two Markdown intake forms are rendered from. Importing it here is what
// makes INV-5 true rather than aspirational: the form, the app and the JSON export cannot drift,
// because there is only one place any of them can drift from. The gate re-renders and diffs.
//
// The import is resolved at build time and inlined into the bundle — no fetch, no network call.
//
// English is the binding language of this repository. German text is a translation and is
// labelled as one wherever it is shown; it is never the source of record. Hypotheses carry no
// German: they are analytical prose where an unmarked translation would quietly become the
// authority, so they stay English and the UI says so.

import source from "../../intake/themes.json";

export type Basis = "fact" | "statement" | "assumption" | "unknown";

/**
 * One filled-in answer. Lives here rather than in App because the deck reads the same
 * structure: the presentation is a projection of these fields, never a rewriting of them.
 */
export interface Answer {
  text: string;
  basis: Basis | null;
  source: string;
  verification: Verification;
}

/** The Entscheidungskopf, keyed by the field slots below. */
export type DecisionHead = Record<string, string>;
export type Verification = "none" | "open" | "blocked";
export type Mode = "triage" | "discovery";
export type Lang = "en" | "de";

/** Every human-readable string in the canonical source carries both languages. */
export interface Text {
  en: string;
  de: string;
}

export const pick = (t: Text, lang: Lang): string => t[lang];

export interface Question {
  id: string;
  text: Text;
  /** Security, data protection, regulation, cost, irreversibility: unknown stays unknown. */
  noDefaults?: boolean;
  modes: Mode[];
  /** Scoping guidance carried by a few questions (Q7.3). English, like the hypotheses. */
  note?: string;
  /** An example of the shape a usable answer has, shown while the field is empty.
      Guidance, never a default: it is not carried into an answer nobody gave. */
  hint?: Text;
}

/** A testable pattern with its boundary — never disguised as a question (INV-6). */
export interface Hypothesis {
  name: string;
  scopeOfValidity: string;
  falsifiableBy: string;
}

/** Theme 2 only: the Entscheidungskopf, filled at intake time. */
export interface DecisionHeadField {
  key: string;
  label: Text;
}

/** Theme 6 only: the mini data inventory, one row per data domain. */
export interface DataInventory {
  columns: string[];
}

export interface Theme {
  id: number;
  slug: string;
  title: Text;
  /** Two sentences: why this block exists at all. */
  why: Text;
  redFlags: Text[];
  stopConditions: Text[];
  hypotheses: Hypothesis[];
  questions: Question[];
  hasDecisionHead: boolean;
  dataInventory?: DataInventory;
}

interface RawQuestion {
  id: string;
  mode: string[];
  no_defaults: boolean;
  text: Text;
  note?: string;
  hint?: Text;
}

interface RawHypothesis {
  name: string;
  scope_of_validity: string;
  falsifiable_by: string;
}

interface RawTheme {
  theme_id: number;
  slug: string;
  title: Text;
  why: Text;
  questions: RawQuestion[];
  hypotheses?: RawHypothesis[];
  red_flags: Text[];
  stop_conditions: Text[];
  decision_head?: unknown;
  data_inventory_annex?: { columns: string[] };
}

/** The YAML block scalars keep their trailing newlines; the UI wants one paragraph. */
const flatten = (s: string): string => s.replace(/\s+/g, " ").trim();

const flattenText = (t: Text): Text => ({ en: flatten(t.en), de: flatten(t.de) });

export const THEMES: Theme[] = (source.themes as RawTheme[]).map((t) => ({
  id: t.theme_id,
  slug: t.slug,
  title: t.title,
  why: flattenText(t.why),
  redFlags: t.red_flags.map(flattenText),
  stopConditions: t.stop_conditions.map(flattenText),
  hypotheses: (t.hypotheses ?? []).map((h) => ({
    name: h.name,
    scopeOfValidity: flatten(h.scope_of_validity),
    falsifiableBy: flatten(h.falsifiable_by),
  })),
  questions: t.questions.map((q) => ({
    id: q.id,
    text: q.text,
    noDefaults: q.no_defaults || undefined,
    modes: q.mode as Mode[],
    note: q.note ? flatten(q.note) : undefined,
    hint: q.hint,
  })),
  hasDecisionHead: t.decision_head !== undefined,
  dataInventory: t.data_inventory_annex
    ? { columns: t.data_inventory_annex.columns }
    : undefined,
}));

/** The Entscheidungskopf slots, in the order the briefing fixes them. */
export const DECISION_HEAD_FIELDS: DecisionHeadField[] = [
  { key: "decision_question", label: { en: "Decision question", de: "Entscheidungsfrage" } },
  { key: "decision_owner", label: { en: "Decision owner", de: "Entscheidungseigner" } },
  { key: "in_scope", label: { en: "In scope", de: "Im Scope" } },
  { key: "out_of_scope", label: { en: "Out of scope", de: "Außerhalb des Scope" } },
  { key: "deadline", label: { en: "Deadline", de: "Frist" } },
];

/** Every question in the set, flat — the deck reads answers by Q-ID. */
export const QUESTIONS_BY_ID: ReadonlyMap<string, Question> = new Map(
  THEMES.flatMap((t) => t.questions.map((q) => [q.id, q] as const)),
);
