"""Shared constants for the Q-ID reference syntax.

The Q-ID is the traceability spine of this kit: every factual claim in a brief must
point back to the intake question that produced it. `QID_PATTERN` is the authoritative
definition — `render_intake.py` and `check.py` both import it from here so the form and
the checker can never drift apart on what counts as a reference.
"""

from __future__ import annotations

import re

# [Q1.1] … [Q10.6]. Deliberately bracket-anchored so a quarter ("Q3 2026") never matches.
QID_PATTERN = re.compile(r"\[Q(?:[1-9]|10)\.\d{1,2}\]")

GENERATED_BANNER = (
    "<!-- generated by tools/render_intake.py from intake/themes/ — do not edit manually -->"
)

# Fixed German machine identifiers. check.py and assertions.yaml locate sections by these
# exact strings; they appear verbatim regardless of the brief's language.
SECTION_LAGEBILD = "## Lagebild"
SECTION_OPTIONS = "## Options-Raum"
SECTION_HYPOTHESEN = "## Hypothesen"
SECTION_RISIKEN = "## Risiken & Rückweg"
SECTION_KONFLIKTE = "## Offene Punkte & Konflikte"
SECTION_TO_VERIFY = "## To-Verify-Register"
SECTION_SIGN_OFF = "## Sign-Off"
